### ISSUE TITLE
Can't get anything to work, can you share the versions of everything you were using? fixed :)

### ISSUE THREAD

**Issue by MichaelWoodc** [TheWhite147/pi-score-counter#11]
Hey, there's too many issues to count with my installation.  

Could you share the versions of everything that you used?  I'm thinking I'll have a much easier time if I install an older pi operating system.  It also seems like the newer versions of python don't like some of this older code

**Comment by TheWhite147** [comment]
Hi, here are the version I used at this time:
- Raspbian 2018-06-27
- Apache 2.4.34
- PHP 7.2.8
- SQLite3 for PHP (i don't know, check the compatible versions with PHP 7.2.8)

**Comment by MichaelWoodc** [comment]
> Hi, here are the version I used at this time:
> 
> * Raspbian 2018-06-27
> * Apache 2.4.34
> * PHP 7.2.8
> * SQLite3 for PHP (i don't know, check the compatible versions with PHP 7.2.8)

sorry one more question, I'm not sure if it matters but do you recall the version of python?
