### ISSUE TITLE
Cannot select player from browser using mouse

### ISSUE THREAD

**Issue by MichaelWoodc** [TheWhite147/pi-score-counter#12]
Everything opens up now and looks good :)  however I cannot select the player with the mouse!  The RFID symbol is flashing but I do not yet have any RFID tags.  Do I need to downgrade to one before the RFID was introduced to use the mouse to select the player?  I was not having luck getting the GPIO buttons to work for some reason, is that the only way to select a player?

**Comment by TheWhite147** [comment]
Yes. The only way to select players is with the GPIO inputs. The buttons.

**Comment by TheWhite147** [comment]
The buttons, or the RFID.
